version: "3.9"
services:
  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      retries: 5

  redis:
    image: redis:7-alpine
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redisdata:/data

  web:
    build: .
    command: ["gunicorn", "tftstats.wsgi:application", "--bind", "0.0.0.0:8000"]
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - .:/code
    ports:
      - "8000:8000"

  worker:
    build: .
    command: ["celery", "-A", "tftstats", "worker", "--loglevel", "info"]
    env_file: .env
    depends_on:
      - web
    volumes:
      - .:/code

volumes:
  pgdata:
  redisdata:
